name: studio-nuxt-build
run-name: studio nuxt build

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Add write workflow permissions
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  # Build job
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        name: Install Bun
        id: bun-install
        with:
          bun-version: 1.0.30

      - name: Install dependencies
        run: bun install

      - name: Install @nuxthq/studio
        run: bun i -D @nuxthq/studio

      - name: Create .nuxtrc
        run: echo $'\nautoImport=true\nmodules[]=@nuxthq/studio' >> .nuxtrc

      - name: Generate
        run: bunx nuxi build --preset github_pages
        env:
          NUXT_PUBLIC_STUDIO_API_URL: https://api.nuxt.studio
          NUXT_PUBLIC_STUDIO_TOKENS: 961720d5f1aea02fd0f1199d5ab12521cc1b60d30e3906893fd9fd38ecbc1bdc

      # Deployment job
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./.output/public
